### ISSUE TITLE
How to handle RateLimit error?

### ISSUE THREAD

**Issue by jacktang** [groq/groq-python#101]
Hello,

First of all, thanks for the Groq platform! I use it as llm backend to create agent. But it often comes up `RateLimit` error. I handled like this:

```
    def inference(self, model: str, messages: list, max_retries:int=5, max_tokens=8000) -> str:
        for i in range(max_retries):
            try:        
                chat_completion = self.client.chat.completions.create(
                    messages=messages,
                    model=model,
                    # temperature=0,
                    max_tokens=max_tokens,
                )
                return chat_completion.choices[0].message.content
            except Exception as e:
                if e.response.status_code == 429:
                    retry_after = e.response.headers['retry-after'] 
                    time.sleep(int(retry_after) + 10)  
```
 But it never works. I have to reconnect it and it works. So how to handle this error?

**Comment by hozen-groq** [comment]
@jacktang Hi there! 👋 First off, thanks for the kind words - we really appreciate it! You can set a retry for tokens exceeded by checking the `x-ratelimit-remaining-tokens` header to see how many tokens you have remaining and retrying according to that. You can see more of the rate limit headers available [here](https://console.groq.com/docs/rate-limits). Hope this helps!
