### ISSUE TITLE
`response_format` in transcriptions seems not working

### ISSUE THREAD

**Issue by Zebartin** [groq/groq-python#107]
I am using Translation to convert speech to text, but the following simple code produces pure text instead of structured json

```python
from groq import Groq

client = Groq()
filename = R'.\short.m4a'

with open(filename, "rb") as file:
    transcription = client.audio.transcriptions.create(
      file=(filename, file.read()),
      model="whisper-large-v3",
      response_format="verbose_json",  # Optional
      language="ja",  # Optional
      temperature=0.0  # Optional
    )
    with open('t.json', 'w', encoding='utf-8') as f:
        f.write(transcription.text)
```

Here is the output and the audio file I used:
```
どうだ2時間前一緒に立ちほやほやのエッジランナーの脳みそから取り出した生の記憶すっげードクほんとやばいBD持ってんなすっげーなこのブリンダンス編集したJKってやつは何しろ無規制だからなマジで脳が痺れる渇きそう完全なサイバーサイコシス野郎頭の中にいたんだからなドール
```

[short.zip](https://github.com/user-attachments/files/16424828/short.zip)

**Comment by Zebartin** [comment]
Besides, is it expected that there is little segmentation in the result?

**Comment by razhangwei** [comment]
Yeah, verbose_json seems only working on playground: https://console.groq.com/playground?model=whisper-large-v3

**Comment by gradenr** [comment]
You are writing `transcription.text` to a file.  If you want the json structured output, you should  use the top-level `transcription` object rather than `transcription.text`

For example:
```python
    for segment in transcription.segments:
        print(segment["start"], segment["text"])
```
