### ISSUE TITLE
AttributeError: 'Groq' object has no attribute 'kwargs'

### ISSUE THREAD

**Issue by simplexityware** [groq/groq-python#109]
I was trying to run the notebook <https://github.com/stanfordnlp/dspy/blob/main/examples/llamaindex/dspy_llamaindex_rag.ipynb> using groq/Llama3 API

```
from llama_index.llms.groq import Groq
llm = Groq(model="llama3-8b-8192", api_key="your_api_key")

from llama_index.core import Settings
Settings.llm = llm
```

However, 
```
output = dspy_qp(query_str="what did the author do in YC")
```

produces the error below

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-29-20d6c9e91a5f>](https://localhost:8080/#) in <cell line: 1>()
----> 1 output = dspy_qp(query_str="what did the author do in YC")

9 frames
[/usr/local/lib/python3.10/dist-packages/dspy/predict/predict.py](https://localhost:8080/#) in forward(self, **kwargs)
     62         # If temperature is 0.0 but its n > 1, set temperature to 0.7.
     63         temperature = config.get("temperature")
---> 64         temperature = lm.kwargs["temperature"] if temperature is None else temperature
     65 
     66         num_generations = config.get("n")

AttributeError: 'Groq' object has no attribute 'kwargs'
```

**Comment by hozen-groq** [comment]
@simplexityware Hi there! Apologies for the radio silence here - were you ever able to get this working? If not, did you or could you please try filing an issue for their repo instead?

**Comment by simplexityware** [comment]
> @simplexityware Hi there! Apologies for the radio silence here - were you ever able to get this working? If not, did you or could you please try filing an issue for their repo instead?

No, I have not repeated the problem since posting this issue. I have resorted to using OpenAI compatible API instead.
