### ISSUE TITLE
Pending tool call

### ISSUE THREAD

**Issue by sus2790** [groq/groq-python#110]
I often got a call_id `pending` tool call, it seems like it is missing <tool-use>:
```py
{
    "tool_call": {
        "id": "pending",
        "type": "function",
        "function": {
            "name": "researches"
        },
        "parameters": {
            "query": "..."
        }
    }
}
</tool-use>
```
Python 3.12.5 & Groq 0.9.0
Pip List: [pastebin](https://pastebin.com/US0AvWGj)
Code: [pastebin](https://pastebin.com/9e0Cr8wN)

**Comment by sus2790** [comment]
any updates?

**Comment by hozen-groq** [comment]
@sus2790 Hi there! 👋  I suggest posting this in the #help channel of our developer community on [Discord](https://discord.gg/invite/groq) if the following suggestions don't help.

I'm wondering if the way you're parsing your function arguments is leading to an issue. You're passing `**function_args` to the function call, but it's a JSON string that needs to be parsed first. Try replacing with:
```
function_args = json.loads(tool_call.function.arguments)
function_response = await function_to_call(**function_args)
```
Also try modifying your `_researches` function to accept `**kwargs`:
```
async def _researches(**kwargs):
    query = kwargs.get('query')
    language = kwargs.get('language', 'zh-TW')
    try:
        result = await researches.asearch(query, hl=language)
        return orjson.dumps({"result": result}).decode("utf-8")
    except Exception as e:
        return orjson.dumps({"error": str(e)}).decode("utf-8")
```

**Comment by sus2790** [comment]
I found a solution [here](https://discord.com/channels/1207099205563457597/1232647310710669422) that seems to have resolved my issue. However, I don’t think this is the best solution. Still, thank you for your help
