### ISSUE TITLE
whisper api fails to use timestamp_granularities

### ISSUE THREAD

**Issue by asmekal** [groq/groq-python#114]
The Whisper API does not work with `timestamp_granularities`, while [documentation](https://console.groq.com/docs/api-reference#audio-transcription) says it's supposed to

```groq.BadRequestError: Error code: 400 - {'error': {'message': '`timestamp_granularities[]` not supported by this model', 'type': 'invalid_request_error'}}```

sample code
```python
client = Groq()
with open(audio_filename_in, 'rb') as audio_file:
    chat_completion = client.audio.transcriptions.create(
        file=audio_file,
        model="whisper-large-v3",
        response_format="verbose_json",
        timestamp_granularities=["word"], # with this line commented works
        language="en",
    )
```

probably related one #107

**Comment by gradenr** [comment]
We only support segment-level timestamps.  Word-level timestamps are on the roadmap.

**Comment by hozen-groq** [comment]
@asmekal Please see the above comment and apologies for the confusion. I've taken a note to update the API reference.

**Comment by ushnah** [comment]
when is the word-level timestamps expected to be added to API?

**Comment by hozen-groq** [comment]
@ushnah The team is looking into it, but no ETA yet due to other priorities. Once we do have them available, I'll make sure to update everyone in our Discord server first under the #announcements channel! Would love for you to [join the community](discord.gg/invite/groq) if you haven't already.

**Comment by villesau** [comment]
@hozen-groq any news about this? :) Would be pretty crucial.
