### ISSUE TITLE
Log Probabilities

### ISSUE THREAD

**Issue by vvenkatesh-ML** [groq/groq-python#25]
Hi There, I am working on a research that involves exploreing log probabilities of LLMs. I see that this a variable for the models, although I this error when I call it: `logprobs` is not supported with this model'. Since these are open-source models, it would be fantastic to have access to the probabilities. Thanks!

**Comment by gradenr** [comment]
Thanks for the feedback. We definitely want to support logprobs.  I have sent this request to the product team.
