### ISSUE TITLE
peer closed connection

### ISSUE THREAD

**Issue by LeventeNagy** [groq/groq-python#26]
Hello

Today I have started to experience the following error 

`httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)`

Would the regarding to an api update? or something from my side?

Tried with the groq-python library and with langchain same results

Thank you

**Comment by gradenr** [comment]
Are you still having this issue?

**Comment by LeventeNagy** [comment]
Sorry for the slow response, no I don't, it stopped the day after I posted it, thank you
