### ISSUE TITLE
Feature request: Streaming with tool calls

### ISSUE THREAD

**Issue by theognis1002** [groq/groq-python#27]
please add streaming with tool calls. This will help greatly for latency in conversations with LLM. Thank you

```
exception=BadRequestError("Error code: 400 - {'error': {'message': 'Tool and function calls do not currently support streaming', 'type': 'invalid_request_error'}}")
```

**Comment by ricklamers** [comment]
On the roadmap!

https://twitter.com/GavinSherry/status/1776290111421829341

**Comment by rodrigoGA** [comment]
@ricklamers Great. For me, this is a limitation. How can I stay informed about the addition of this feature? I hope that subscribing to the request will be enough

**Comment by ricklamers** [comment]
We now support it!

https://x.com/GitMaxd/status/1791577093043863876
