### ISSUE TITLE
Support for smith.langchain.com tracing

### ISSUE THREAD

**Issue by andraz** [groq/groq-python#28]
When connecting to Groq using the `langchain_openai` lib like this:

```py
from langchain_openai import ChatOpenAI
from agent.config import groq_api_key

model_name = "mixtral-8x7b-32768"
api_base_url = "https://api.groq.com/openai/v1"

model = ChatOpenAI(
    model=model_name, openai_api_base=api_base_url, openai_api_key=groq_api_key
)

```

with `.env` file:

```
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
LANGCHAIN_API_KEY=ls_********************************************

GROQ_API_KEY=gsk_********************************************
```

I am able to trace the logs of my tool calling:

![image](https://github.com/groq/groq-python/assets/8480981/7027d683-f1f9-46c7-8ca9-3d36bb55c744)

How to enable this feature using the initialization below?

```py
from groq import Groq
import os
import json

client = Groq(api_key = os.getenv('GROQ_API_KEY'))
MODEL = 'mixtral-8x7b-32768'

# ...
```
source: https://console.groq.com/docs/tool-use#example

**Comment by jacoblee93** [comment]
Hey @andraz!

You would want to use the `langchain-groq` package as shown here:

https://python.langchain.com/docs/integrations/providers/groq/

Or you can use the `@traceable` decorator here:

https://docs.smith.langchain.com/tracing/faq/logging_and_viewing#the-traceable-decorator

**Comment by hozen-groq** [comment]
Hi, @andraz! 😁 Does the above answer your question?

**Comment by andraz** [comment]
Hi @jacoblee93 and @hozen-groq, thanks for your support. Sadly I had no success in making this work. Neither using `langchain-groq` and adding a `@traceable` decorator in front of LLM call helped, execution still produces zero logs.

**Comment by jacoblee93** [comment]
And env vars are set? Should be the exact same flow, and I'm quite surprised traces are working elsewhere in that case...
