### ISSUE TITLE
Content Extraction Issue

### ISSUE THREAD

**Issue by CYFARE** [groq/groq-python#29]
Hi Groq Team,

### Issue

I'm trying to make API responses usable but so far have failed to extract the information inside "content=" part of responses properly. I'm using the following code:

![image](https://github.com/groq/groq-python/assets/150654459/3b5685ff-4359-4144-8c3e-5059cbb973dc)

I have tested the following for extraction but none of them sattify multi-line extraction:

```python
    extracted_content = re.search(r'content="([\s\S]*?)" response_metadata', content).group(1)

    extracted_content = re.search(r'content=[\'"]([^\'"]*)[\'"]', content).group(1)
    clean_content = re.sub(r'\s+response_metadata=\{.*\}$', '', extracted_content, flags=re.DOTALL)

    extracted_content = re.search(r'content=[\'"]([^\'"]*)[\'"]', content).group(1)
    clean_content = re.sub(r'\s+response_metadata=\{.*\}$', '', extracted_content, flags=re.DOTALL)

    extracted_content = re.search(r'content="([^"]*)"', content).group(1)
    clean_content = re.sub(r'\s+response_metadata=\{.*\}$', '', extracted_content, flags=re.DOTALL)
```

I've also tried dumping this into json dict, but for different types of responses, edge-cases are making extraction inaccurate, for example, only half the content is extracted due to some "'" or "\\" character inside answers and so on..

### Sample Response

The following is my sample query & associated api response:

![image](https://github.com/groq/groq-python/assets/150654459/9e50d515-a421-4a12-942f-779f5327ce2f)

I want to only get the answer inside content= either directly through API response or if you have any python function/solution to extract this value under different edge-cases, for example, when the answer has multiple lines and multiple code blocks or when the answer has different encoding types.

Thanks in advance!

**Comment by gradenr** [comment]
Have you tried using `with_structured_output` to apply a schema to the content?  https://python.langchain.com/docs/modules/model_io/chat/structured_output/#json-mode-2

This will allow you to specify a schema in which you want the model to respond.

**Comment by CYFARE** [comment]
Well, idk if something was changed from API backend, but now the answers are direct when using llama3 model :+1: 

![image](https://github.com/groq/groq-python/assets/150654459/8773aec0-d135-46cf-b781-abedd83f886d)

Thanks for the help!
