### ISSUE TITLE
Is there a way to adjust the logit likliehood using the groq api

### ISSUE THREAD

**Issue by psych0v0yager** [groq/groq-python#31]
I am planning to add groq support into the constrained generation library outlines. https://github.com/outlines-dev/outlines
Outlines already has OpenAI support so the change should be very straightforward except for the following issue

The documentation for groq says the following features are not supported in the groq api

logprobs
logit_bias
top_logprobs

https://console.groq.com/docs/openai

Is there an alternative way to adjust the logit probabilities in groq or is it currently not supported?

**Comment by gradenr** [comment]
This is on the roadmap, but is not currently available with our API.  I have shared this requests with our product team.
