### ISSUE TITLE
Support for regular completion API (not ChatCompletion)

### ISSUE THREAD

**Issue by jinyongyoo** [groq/groq-python#33]
Hi, I was wondering if you would consider supporting regular completion API too so that we can provide raw prompts instead of relying on the chat completion format.

While chat completion style APIs are the norm, I think there are still edge cases were developers want full control of the prompt (e.g. passing a prefix for the assistant's output to ensure reliable generation).

**Comment by hozen-groq** [comment]
@jinyongyoo Hi there! 👋 Apologies for the delay in response here, but really appreciate the request and use case insight. I believe we have had this as a feature request that was posted to our #feature-requests channel in our [Discord server](https://discord.gg/invit/groq), which we triage and pass onto our Product and Engineering teams. Please join our dev community there if you haven't already and upvote any other features you'd like to see!
