### ISSUE TITLE
Model not found for Whisper 

### ISSUE THREAD

**Issue by darkzbaron** [groq/groq-python#85]
groq.NotFoundError: Error code: 404 - {'error': {'message': 'The model `whisper-large-v3` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'code': 'model_not_found'}}

**Comment by gradenr** [comment]
Thank you for your interest in whisper. This model is not generally available, but you can request access by contacting support@groq.com.  Please include your [organization id](https://console.groq.com/settings/organization) in your email to streamline the approval process.

**Comment by gradenr** [comment]
Whisper has been publicly released and you shuld have access now.

**Comment by darkzbaron** [comment]
Thanks, it's fast! However, there is no vtt or srt as specified in the documentation!
